version: 2
updates:
- package-ecosystem: nuget
  directory: "/ServiceItemsPlanningPlugin"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/ServiceItemsPlanningPlugin.Integration.Test"
  schedule:
    interval: daily